// Capital city + top largest cities per state, deduped, kebab-case slugs.
// Used only by the two CORE solutions: owner-operator-recruiting + cdl-driver-hiring.

export type City = { slug: string; name: string; isCapital?: boolean };

export const CITIES_BY_STATE: Record<string, City[]> = {
  texas: [
    { slug: "houston", name: "Houston" },
    { slug: "san-antonio", name: "San Antonio" },
    { slug: "dallas", name: "Dallas" },
    { slug: "austin", name: "Austin", isCapital: true },
    { slug: "fort-worth", name: "Fort Worth" },
    { slug: "el-paso", name: "El Paso" },
    { slug: "arlington", name: "Arlington" },
    { slug: "corpus-christi", name: "Corpus Christi" },
    { slug: "plano", name: "Plano" },
    { slug: "laredo", name: "Laredo" },
    { slug: "lubbock", name: "Lubbock" },
  ],
  california: [
    { slug: "los-angeles", name: "Los Angeles" },
    { slug: "san-diego", name: "San Diego" },
    { slug: "san-jose", name: "San Jose" },
    { slug: "san-francisco", name: "San Francisco" },
    { slug: "fresno", name: "Fresno" },
    { slug: "sacramento", name: "Sacramento", isCapital: true },
    { slug: "long-beach", name: "Long Beach" },
    { slug: "oakland", name: "Oakland" },
    { slug: "bakersfield", name: "Bakersfield" },
    { slug: "anaheim", name: "Anaheim" },
    { slug: "riverside", name: "Riverside" },
  ],
  florida: [
    { slug: "jacksonville", name: "Jacksonville" },
    { slug: "miami", name: "Miami" },
    { slug: "tampa", name: "Tampa" },
    { slug: "orlando", name: "Orlando" },
    { slug: "st-petersburg", name: "St. Petersburg" },
    { slug: "hialeah", name: "Hialeah" },
    { slug: "tallahassee", name: "Tallahassee", isCapital: true },
    { slug: "port-st-lucie", name: "Port St. Lucie" },
    { slug: "fort-lauderdale", name: "Fort Lauderdale" },
    { slug: "cape-coral", name: "Cape Coral" },
    { slug: "pembroke-pines", name: "Pembroke Pines" },
  ],
  illinois: [
    { slug: "chicago", name: "Chicago" },
    { slug: "aurora", name: "Aurora" },
    { slug: "joliet", name: "Joliet" },
    { slug: "naperville", name: "Naperville" },
    { slug: "rockford", name: "Rockford" },
    { slug: "elgin", name: "Elgin" },
    { slug: "springfield", name: "Springfield", isCapital: true },
    { slug: "peoria", name: "Peoria" },
    { slug: "champaign", name: "Champaign" },
    { slug: "waukegan", name: "Waukegan" },
    { slug: "cicero", name: "Cicero" },
  ],
  georgia: [
    { slug: "atlanta", name: "Atlanta", isCapital: true },
    { slug: "augusta", name: "Augusta" },
    { slug: "columbus", name: "Columbus" },
    { slug: "macon", name: "Macon" },
    { slug: "savannah", name: "Savannah" },
    { slug: "athens", name: "Athens" },
    { slug: "sandy-springs", name: "Sandy Springs" },
    { slug: "roswell", name: "Roswell" },
    { slug: "warner-robins", name: "Warner Robins" },
    { slug: "albany", name: "Albany" },
    { slug: "johns-creek", name: "Johns Creek" },
  ],
  pennsylvania: [
    { slug: "philadelphia", name: "Philadelphia" },
    { slug: "pittsburgh", name: "Pittsburgh" },
    { slug: "allentown", name: "Allentown" },
    { slug: "erie", name: "Erie" },
    { slug: "reading", name: "Reading" },
    { slug: "scranton", name: "Scranton" },
    { slug: "bethlehem", name: "Bethlehem" },
    { slug: "lancaster", name: "Lancaster" },
    { slug: "harrisburg", name: "Harrisburg", isCapital: true },
    { slug: "york", name: "York" },
    { slug: "altoona", name: "Altoona" },
  ],
  ohio: [
    { slug: "columbus", name: "Columbus", isCapital: true },
    { slug: "cleveland", name: "Cleveland" },
    { slug: "cincinnati", name: "Cincinnati" },
    { slug: "toledo", name: "Toledo" },
    { slug: "akron", name: "Akron" },
    { slug: "dayton", name: "Dayton" },
    { slug: "parma", name: "Parma" },
    { slug: "canton", name: "Canton" },
    { slug: "youngstown", name: "Youngstown" },
    { slug: "lorain", name: "Lorain" },
    { slug: "hamilton", name: "Hamilton" },
  ],
  "north-carolina": [
    { slug: "charlotte", name: "Charlotte" },
    { slug: "raleigh", name: "Raleigh", isCapital: true },
    { slug: "greensboro", name: "Greensboro" },
    { slug: "durham", name: "Durham" },
    { slug: "winston-salem", name: "Winston-Salem" },
    { slug: "fayetteville", name: "Fayetteville" },
    { slug: "cary", name: "Cary" },
    { slug: "wilmington", name: "Wilmington" },
    { slug: "high-point", name: "High Point" },
    { slug: "concord", name: "Concord" },
    { slug: "asheville", name: "Asheville" },
  ],
  indiana: [
    { slug: "indianapolis", name: "Indianapolis", isCapital: true },
    { slug: "fort-wayne", name: "Fort Wayne" },
    { slug: "evansville", name: "Evansville" },
    { slug: "south-bend", name: "South Bend" },
    { slug: "carmel", name: "Carmel" },
    { slug: "fishers", name: "Fishers" },
    { slug: "bloomington", name: "Bloomington" },
    { slug: "hammond", name: "Hammond" },
    { slug: "gary", name: "Gary" },
    { slug: "lafayette", name: "Lafayette" },
    { slug: "muncie", name: "Muncie" },
  ],
  tennessee: [
    { slug: "nashville", name: "Nashville", isCapital: true },
    { slug: "memphis", name: "Memphis" },
    { slug: "knoxville", name: "Knoxville" },
    { slug: "chattanooga", name: "Chattanooga" },
    { slug: "clarksville", name: "Clarksville" },
    { slug: "murfreesboro", name: "Murfreesboro" },
    { slug: "franklin", name: "Franklin" },
    { slug: "jackson", name: "Jackson" },
    { slug: "johnson-city", name: "Johnson City" },
    { slug: "kingsport", name: "Kingsport" },
    { slug: "bartlett", name: "Bartlett" },
  ],
  michigan: [
    { slug: "detroit", name: "Detroit" },
    { slug: "grand-rapids", name: "Grand Rapids" },
    { slug: "warren", name: "Warren" },
    { slug: "sterling-heights", name: "Sterling Heights" },
    { slug: "ann-arbor", name: "Ann Arbor" },
    { slug: "lansing", name: "Lansing", isCapital: true },
    { slug: "flint", name: "Flint" },
    { slug: "dearborn", name: "Dearborn" },
    { slug: "livonia", name: "Livonia" },
    { slug: "troy", name: "Troy" },
    { slug: "westland", name: "Westland" },
  ],
  arizona: [
    { slug: "phoenix", name: "Phoenix", isCapital: true },
    { slug: "tucson", name: "Tucson" },
    { slug: "mesa", name: "Mesa" },
    { slug: "chandler", name: "Chandler" },
    { slug: "gilbert", name: "Gilbert" },
    { slug: "glendale", name: "Glendale" },
    { slug: "scottsdale", name: "Scottsdale" },
    { slug: "peoria", name: "Peoria" },
    { slug: "tempe", name: "Tempe" },
    { slug: "surprise", name: "Surprise" },
    { slug: "yuma", name: "Yuma" },
  ],
  "new-jersey": [
    { slug: "newark", name: "Newark" },
    { slug: "jersey-city", name: "Jersey City" },
    { slug: "paterson", name: "Paterson" },
    { slug: "elizabeth", name: "Elizabeth" },
    { slug: "lakewood", name: "Lakewood" },
    { slug: "edison", name: "Edison" },
    { slug: "woodbridge", name: "Woodbridge" },
    { slug: "toms-river", name: "Toms River" },
    { slug: "hamilton", name: "Hamilton" },
    { slug: "trenton", name: "Trenton", isCapital: true },
    { slug: "clifton", name: "Clifton" },
  ],
  "new-york": [
    { slug: "new-york-city", name: "New York City" },
    { slug: "buffalo", name: "Buffalo" },
    { slug: "yonkers", name: "Yonkers" },
    { slug: "rochester", name: "Rochester" },
    { slug: "syracuse", name: "Syracuse" },
    { slug: "albany", name: "Albany", isCapital: true },
    { slug: "new-rochelle", name: "New Rochelle" },
    { slug: "mount-vernon", name: "Mount Vernon" },
    { slug: "schenectady", name: "Schenectady" },
    { slug: "utica", name: "Utica" },
    { slug: "white-plains", name: "White Plains" },
  ],
  virginia: [
    { slug: "virginia-beach", name: "Virginia Beach" },
    { slug: "chesapeake", name: "Chesapeake" },
    { slug: "norfolk", name: "Norfolk" },
    { slug: "arlington", name: "Arlington" },
    { slug: "richmond", name: "Richmond", isCapital: true },
    { slug: "newport-news", name: "Newport News" },
    { slug: "alexandria", name: "Alexandria" },
    { slug: "hampton", name: "Hampton" },
    { slug: "roanoke", name: "Roanoke" },
    { slug: "portsmouth", name: "Portsmouth" },
    { slug: "suffolk", name: "Suffolk" },
  ],
  missouri: [
    { slug: "kansas-city", name: "Kansas City" },
    { slug: "st-louis", name: "St. Louis" },
    { slug: "springfield", name: "Springfield" },
    { slug: "columbia", name: "Columbia" },
    { slug: "independence", name: "Independence" },
    { slug: "lees-summit", name: "Lee's Summit" },
    { slug: "ofallon", name: "O'Fallon" },
    { slug: "st-joseph", name: "St. Joseph" },
    { slug: "st-charles", name: "St. Charles" },
    { slug: "jefferson-city", name: "Jefferson City", isCapital: true },
    { slug: "blue-springs", name: "Blue Springs" },
  ],
  oklahoma: [
    { slug: "oklahoma-city", name: "Oklahoma City", isCapital: true },
    { slug: "tulsa", name: "Tulsa" },
    { slug: "norman", name: "Norman" },
    { slug: "broken-arrow", name: "Broken Arrow" },
    { slug: "edmond", name: "Edmond" },
    { slug: "lawton", name: "Lawton" },
    { slug: "moore", name: "Moore" },
    { slug: "midwest-city", name: "Midwest City" },
    { slug: "enid", name: "Enid" },
    { slug: "stillwater", name: "Stillwater" },
    { slug: "muskogee", name: "Muskogee" },
  ],
  arkansas: [
    { slug: "little-rock", name: "Little Rock", isCapital: true },
    { slug: "fort-smith", name: "Fort Smith" },
    { slug: "fayetteville", name: "Fayetteville" },
    { slug: "springdale", name: "Springdale" },
    { slug: "jonesboro", name: "Jonesboro" },
    { slug: "north-little-rock", name: "North Little Rock" },
    { slug: "conway", name: "Conway" },
    { slug: "rogers", name: "Rogers" },
    { slug: "bentonville", name: "Bentonville" },
    { slug: "pine-bluff", name: "Pine Bluff" },
    { slug: "hot-springs", name: "Hot Springs" },
  ],
  kentucky: [
    { slug: "louisville", name: "Louisville" },
    { slug: "lexington", name: "Lexington" },
    { slug: "bowling-green", name: "Bowling Green" },
    { slug: "owensboro", name: "Owensboro" },
    { slug: "covington", name: "Covington" },
    { slug: "georgetown", name: "Georgetown" },
    { slug: "richmond", name: "Richmond" },
    { slug: "hopkinsville", name: "Hopkinsville" },
    { slug: "florence", name: "Florence" },
    { slug: "henderson", name: "Henderson" },
    { slug: "frankfort", name: "Frankfort", isCapital: true },
  ],
  "south-carolina": [
    { slug: "charleston", name: "Charleston" },
    { slug: "columbia", name: "Columbia", isCapital: true },
    { slug: "north-charleston", name: "North Charleston" },
    { slug: "mount-pleasant", name: "Mount Pleasant" },
    { slug: "rock-hill", name: "Rock Hill" },
    { slug: "greenville", name: "Greenville" },
    { slug: "summerville", name: "Summerville" },
    { slug: "goose-creek", name: "Goose Creek" },
    { slug: "sumter", name: "Sumter" },
    { slug: "hilton-head-island", name: "Hilton Head Island" },
    { slug: "florence", name: "Florence" },
  ],
  washington: [
    { slug: "seattle", name: "Seattle" },
    { slug: "spokane", name: "Spokane" },
    { slug: "tacoma", name: "Tacoma" },
    { slug: "vancouver", name: "Vancouver" },
    { slug: "bellevue", name: "Bellevue" },
    { slug: "kent", name: "Kent" },
    { slug: "everett", name: "Everett" },
    { slug: "renton", name: "Renton" },
    { slug: "olympia", name: "Olympia", isCapital: true },
    { slug: "yakima", name: "Yakima" },
    { slug: "bellingham", name: "Bellingham" },
  ],
  alabama: [
    { slug: "huntsville", name: "Huntsville" },
    { slug: "birmingham", name: "Birmingham" },
    { slug: "montgomery", name: "Montgomery", isCapital: true },
    { slug: "mobile", name: "Mobile" },
    { slug: "tuscaloosa", name: "Tuscaloosa" },
    { slug: "hoover", name: "Hoover" },
    { slug: "auburn", name: "Auburn" },
    { slug: "dothan", name: "Dothan" },
    { slug: "decatur", name: "Decatur" },
    { slug: "madison", name: "Madison" },
    { slug: "florence", name: "Florence" },
  ],
  louisiana: [
    { slug: "new-orleans", name: "New Orleans" },
    { slug: "baton-rouge", name: "Baton Rouge", isCapital: true },
    { slug: "shreveport", name: "Shreveport" },
    { slug: "metairie", name: "Metairie" },
    { slug: "lafayette", name: "Lafayette" },
    { slug: "lake-charles", name: "Lake Charles" },
    { slug: "kenner", name: "Kenner" },
    { slug: "bossier-city", name: "Bossier City" },
    { slug: "monroe", name: "Monroe" },
    { slug: "alexandria", name: "Alexandria" },
    { slug: "houma", name: "Houma" },
  ],
  oregon: [
    { slug: "portland", name: "Portland" },
    { slug: "salem", name: "Salem", isCapital: true },
    { slug: "eugene", name: "Eugene" },
    { slug: "gresham", name: "Gresham" },
    { slug: "hillsboro", name: "Hillsboro" },
    { slug: "beaverton", name: "Beaverton" },
    { slug: "bend", name: "Bend" },
    { slug: "medford", name: "Medford" },
    { slug: "springfield", name: "Springfield" },
    { slug: "corvallis", name: "Corvallis" },
    { slug: "albany", name: "Albany" },
  ],
  colorado: [
    { slug: "denver", name: "Denver", isCapital: true },
    { slug: "colorado-springs", name: "Colorado Springs" },
    { slug: "aurora", name: "Aurora" },
    { slug: "fort-collins", name: "Fort Collins" },
    { slug: "lakewood", name: "Lakewood" },
    { slug: "thornton", name: "Thornton" },
    { slug: "arvada", name: "Arvada" },
    { slug: "westminster", name: "Westminster" },
    { slug: "pueblo", name: "Pueblo" },
    { slug: "centennial", name: "Centennial" },
    { slug: "boulder", name: "Boulder" },
  ],
  minnesota: [
    { slug: "minneapolis", name: "Minneapolis" },
    { slug: "st-paul", name: "St. Paul", isCapital: true },
    { slug: "rochester", name: "Rochester" },
    { slug: "duluth", name: "Duluth" },
    { slug: "bloomington", name: "Bloomington" },
    { slug: "brooklyn-park", name: "Brooklyn Park" },
    { slug: "plymouth", name: "Plymouth" },
    { slug: "maple-grove", name: "Maple Grove" },
    { slug: "woodbury", name: "Woodbury" },
    { slug: "st-cloud", name: "St. Cloud" },
    { slug: "eagan", name: "Eagan" },
  ],
  wisconsin: [
    { slug: "milwaukee", name: "Milwaukee" },
    { slug: "madison", name: "Madison", isCapital: true },
    { slug: "green-bay", name: "Green Bay" },
    { slug: "kenosha", name: "Kenosha" },
    { slug: "racine", name: "Racine" },
    { slug: "appleton", name: "Appleton" },
    { slug: "waukesha", name: "Waukesha" },
    { slug: "eau-claire", name: "Eau Claire" },
    { slug: "oshkosh", name: "Oshkosh" },
    { slug: "janesville", name: "Janesville" },
    { slug: "west-allis", name: "West Allis" },
  ],
  iowa: [
    { slug: "des-moines", name: "Des Moines", isCapital: true },
    { slug: "cedar-rapids", name: "Cedar Rapids" },
    { slug: "davenport", name: "Davenport" },
    { slug: "sioux-city", name: "Sioux City" },
    { slug: "iowa-city", name: "Iowa City" },
    { slug: "waterloo", name: "Waterloo" },
    { slug: "ankeny", name: "Ankeny" },
    { slug: "council-bluffs", name: "Council Bluffs" },
    { slug: "west-des-moines", name: "West Des Moines" },
    { slug: "dubuque", name: "Dubuque" },
    { slug: "ames", name: "Ames" },
  ],
  kansas: [
    { slug: "wichita", name: "Wichita" },
    { slug: "overland-park", name: "Overland Park" },
    { slug: "kansas-city", name: "Kansas City" },
    { slug: "olathe", name: "Olathe" },
    { slug: "topeka", name: "Topeka", isCapital: true },
    { slug: "lawrence", name: "Lawrence" },
    { slug: "shawnee", name: "Shawnee" },
    { slug: "manhattan", name: "Manhattan" },
    { slug: "lenexa", name: "Lenexa" },
    { slug: "salina", name: "Salina" },
    { slug: "hutchinson", name: "Hutchinson" },
  ],
  nebraska: [
    { slug: "omaha", name: "Omaha" },
    { slug: "lincoln", name: "Lincoln", isCapital: true },
    { slug: "bellevue", name: "Bellevue" },
    { slug: "grand-island", name: "Grand Island" },
    { slug: "kearney", name: "Kearney" },
    { slug: "fremont", name: "Fremont" },
    { slug: "hastings", name: "Hastings" },
    { slug: "north-platte", name: "North Platte" },
    { slug: "norfolk", name: "Norfolk" },
    { slug: "papillion", name: "Papillion" },
    { slug: "columbus", name: "Columbus" },
  ],
  maryland: [
    { slug: "baltimore", name: "Baltimore" },
    { slug: "frederick", name: "Frederick" },
    { slug: "rockville", name: "Rockville" },
    { slug: "gaithersburg", name: "Gaithersburg" },
    { slug: "bowie", name: "Bowie" },
    { slug: "hagerstown", name: "Hagerstown" },
    { slug: "annapolis", name: "Annapolis", isCapital: true },
    { slug: "salisbury", name: "Salisbury" },
    { slug: "college-park", name: "College Park" },
    { slug: "cumberland", name: "Cumberland" },
    { slug: "westminster", name: "Westminster" },
  ],
  utah: [
    { slug: "salt-lake-city", name: "Salt Lake City", isCapital: true },
    { slug: "west-valley-city", name: "West Valley City" },
    { slug: "west-jordan", name: "West Jordan" },
    { slug: "provo", name: "Provo" },
    { slug: "orem", name: "Orem" },
    { slug: "sandy", name: "Sandy" },
    { slug: "st-george", name: "St. George" },
    { slug: "ogden", name: "Ogden" },
    { slug: "layton", name: "Layton" },
    { slug: "lehi", name: "Lehi" },
    { slug: "south-jordan", name: "South Jordan" },
  ],
  nevada: [
    { slug: "las-vegas", name: "Las Vegas" },
    { slug: "henderson", name: "Henderson" },
    { slug: "reno", name: "Reno" },
    { slug: "north-las-vegas", name: "North Las Vegas" },
    { slug: "sparks", name: "Sparks" },
    { slug: "carson-city", name: "Carson City", isCapital: true },
    { slug: "fernley", name: "Fernley" },
    { slug: "elko", name: "Elko" },
    { slug: "mesquite", name: "Mesquite" },
    { slug: "boulder-city", name: "Boulder City" },
    { slug: "fallon", name: "Fallon" },
  ],
  mississippi: [
    { slug: "jackson", name: "Jackson", isCapital: true },
    { slug: "gulfport", name: "Gulfport" },
    { slug: "southaven", name: "Southaven" },
    { slug: "hattiesburg", name: "Hattiesburg" },
    { slug: "biloxi", name: "Biloxi" },
    { slug: "meridian", name: "Meridian" },
    { slug: "tupelo", name: "Tupelo" },
    { slug: "greenville", name: "Greenville" },
    { slug: "olive-branch", name: "Olive Branch" },
    { slug: "horn-lake", name: "Horn Lake" },
    { slug: "pearl", name: "Pearl" },
  ],
  connecticut: [
    { slug: "bridgeport", name: "Bridgeport" },
    { slug: "new-haven", name: "New Haven" },
    { slug: "hartford", name: "Hartford", isCapital: true },
    { slug: "stamford", name: "Stamford" },
    { slug: "waterbury", name: "Waterbury" },
    { slug: "norwalk", name: "Norwalk" },
    { slug: "danbury", name: "Danbury" },
    { slug: "new-britain", name: "New Britain" },
    { slug: "bristol", name: "Bristol" },
    { slug: "meriden", name: "Meriden" },
    { slug: "west-haven", name: "West Haven" },
  ],
  massachusetts: [
    { slug: "boston", name: "Boston", isCapital: true },
    { slug: "worcester", name: "Worcester" },
    { slug: "springfield", name: "Springfield" },
    { slug: "cambridge", name: "Cambridge" },
    { slug: "lowell", name: "Lowell" },
    { slug: "brockton", name: "Brockton" },
    { slug: "quincy", name: "Quincy" },
    { slug: "new-bedford", name: "New Bedford" },
    { slug: "lynn", name: "Lynn" },
    { slug: "fall-river", name: "Fall River" },
    { slug: "newton", name: "Newton" },
  ],
  "new-hampshire": [
    { slug: "manchester", name: "Manchester" },
    { slug: "nashua", name: "Nashua" },
    { slug: "concord", name: "Concord", isCapital: true },
    { slug: "dover", name: "Dover" },
    { slug: "rochester", name: "Rochester" },
    { slug: "keene", name: "Keene" },
    { slug: "portsmouth", name: "Portsmouth" },
    { slug: "laconia", name: "Laconia" },
    { slug: "lebanon", name: "Lebanon" },
    { slug: "claremont", name: "Claremont" },
    { slug: "somersworth", name: "Somersworth" },
  ],
  maine: [
    { slug: "portland", name: "Portland" },
    { slug: "lewiston", name: "Lewiston" },
    { slug: "bangor", name: "Bangor" },
    { slug: "south-portland", name: "South Portland" },
    { slug: "auburn", name: "Auburn" },
    { slug: "biddeford", name: "Biddeford" },
    { slug: "sanford", name: "Sanford" },
    { slug: "augusta", name: "Augusta", isCapital: true },
    { slug: "saco", name: "Saco" },
    { slug: "waterville", name: "Waterville" },
    { slug: "westbrook", name: "Westbrook" },
  ],
  vermont: [
    { slug: "burlington", name: "Burlington" },
    { slug: "south-burlington", name: "South Burlington" },
    { slug: "rutland", name: "Rutland" },
    { slug: "essex-junction", name: "Essex Junction" },
    { slug: "barre", name: "Barre" },
    { slug: "montpelier", name: "Montpelier", isCapital: true },
    { slug: "winooski", name: "Winooski" },
    { slug: "st-albans", name: "St. Albans" },
    { slug: "newport", name: "Newport" },
    { slug: "vergennes", name: "Vergennes" },
    { slug: "brattleboro", name: "Brattleboro" },
  ],
  "rhode-island": [
    { slug: "providence", name: "Providence", isCapital: true },
    { slug: "warwick", name: "Warwick" },
    { slug: "cranston", name: "Cranston" },
    { slug: "pawtucket", name: "Pawtucket" },
    { slug: "east-providence", name: "East Providence" },
    { slug: "woonsocket", name: "Woonsocket" },
    { slug: "newport", name: "Newport" },
    { slug: "central-falls", name: "Central Falls" },
    { slug: "westerly", name: "Westerly" },
    { slug: "north-providence", name: "North Providence" },
    { slug: "cumberland", name: "Cumberland" },
  ],
  delaware: [
    { slug: "wilmington", name: "Wilmington" },
    { slug: "dover", name: "Dover", isCapital: true },
    { slug: "newark", name: "Newark" },
    { slug: "middletown", name: "Middletown" },
    { slug: "smyrna", name: "Smyrna" },
    { slug: "milford", name: "Milford" },
    { slug: "seaford", name: "Seaford" },
    { slug: "georgetown", name: "Georgetown" },
    { slug: "elsmere", name: "Elsmere" },
    { slug: "new-castle", name: "New Castle" },
    { slug: "lewes", name: "Lewes" },
  ],
  "west-virginia": [
    { slug: "charleston", name: "Charleston", isCapital: true },
    { slug: "huntington", name: "Huntington" },
    { slug: "morgantown", name: "Morgantown" },
    { slug: "parkersburg", name: "Parkersburg" },
    { slug: "wheeling", name: "Wheeling" },
    { slug: "weirton", name: "Weirton" },
    { slug: "fairmont", name: "Fairmont" },
    { slug: "martinsburg", name: "Martinsburg" },
    { slug: "beckley", name: "Beckley" },
    { slug: "clarksburg", name: "Clarksburg" },
    { slug: "south-charleston", name: "South Charleston" },
  ],
  idaho: [
    { slug: "boise", name: "Boise", isCapital: true },
    { slug: "meridian", name: "Meridian" },
    { slug: "nampa", name: "Nampa" },
    { slug: "idaho-falls", name: "Idaho Falls" },
    { slug: "caldwell", name: "Caldwell" },
    { slug: "pocatello", name: "Pocatello" },
    { slug: "coeur-dalene", name: "Coeur d'Alene" },
    { slug: "twin-falls", name: "Twin Falls" },
    { slug: "lewiston", name: "Lewiston" },
    { slug: "post-falls", name: "Post Falls" },
    { slug: "rexburg", name: "Rexburg" },
  ],
  montana: [
    { slug: "billings", name: "Billings" },
    { slug: "missoula", name: "Missoula" },
    { slug: "great-falls", name: "Great Falls" },
    { slug: "bozeman", name: "Bozeman" },
    { slug: "butte", name: "Butte" },
    { slug: "helena", name: "Helena", isCapital: true },
    { slug: "kalispell", name: "Kalispell" },
    { slug: "havre", name: "Havre" },
    { slug: "anaconda", name: "Anaconda" },
    { slug: "miles-city", name: "Miles City" },
    { slug: "belgrade", name: "Belgrade" },
  ],
  wyoming: [
    { slug: "cheyenne", name: "Cheyenne", isCapital: true },
    { slug: "casper", name: "Casper" },
    { slug: "laramie", name: "Laramie" },
    { slug: "gillette", name: "Gillette" },
    { slug: "rock-springs", name: "Rock Springs" },
    { slug: "sheridan", name: "Sheridan" },
    { slug: "green-river", name: "Green River" },
    { slug: "evanston", name: "Evanston" },
    { slug: "riverton", name: "Riverton" },
    { slug: "jackson", name: "Jackson" },
    { slug: "cody", name: "Cody" },
  ],
  "north-dakota": [
    { slug: "fargo", name: "Fargo" },
    { slug: "bismarck", name: "Bismarck", isCapital: true },
    { slug: "grand-forks", name: "Grand Forks" },
    { slug: "minot", name: "Minot" },
    { slug: "west-fargo", name: "West Fargo" },
    { slug: "williston", name: "Williston" },
    { slug: "mandan", name: "Mandan" },
    { slug: "dickinson", name: "Dickinson" },
    { slug: "jamestown", name: "Jamestown" },
    { slug: "wahpeton", name: "Wahpeton" },
    { slug: "devils-lake", name: "Devils Lake" },
  ],
  "south-dakota": [
    { slug: "sioux-falls", name: "Sioux Falls" },
    { slug: "rapid-city", name: "Rapid City" },
    { slug: "aberdeen", name: "Aberdeen" },
    { slug: "brookings", name: "Brookings" },
    { slug: "watertown", name: "Watertown" },
    { slug: "mitchell", name: "Mitchell" },
    { slug: "pierre", name: "Pierre", isCapital: true },
    { slug: "yankton", name: "Yankton" },
    { slug: "huron", name: "Huron" },
    { slug: "vermillion", name: "Vermillion" },
    { slug: "spearfish", name: "Spearfish" },
  ],
  "new-mexico": [
    { slug: "albuquerque", name: "Albuquerque" },
    { slug: "las-cruces", name: "Las Cruces" },
    { slug: "rio-rancho", name: "Rio Rancho" },
    { slug: "santa-fe", name: "Santa Fe", isCapital: true },
    { slug: "roswell", name: "Roswell" },
    { slug: "farmington", name: "Farmington" },
    { slug: "south-valley", name: "South Valley" },
    { slug: "clovis", name: "Clovis" },
    { slug: "hobbs", name: "Hobbs" },
    { slug: "alamogordo", name: "Alamogordo" },
    { slug: "carlsbad", name: "Carlsbad" },
  ],
};

// Helpers
export function citiesForState(stateSlug: string): City[] {
  return CITIES_BY_STATE[stateSlug] ?? [];
}

export function getCity(stateSlug: string, citySlug: string): City | undefined {
  return citiesForState(stateSlug).find((c) => c.slug === citySlug);
}

// All (stateSlug, citySlug) pairs for generateStaticParams
export function allCityPairs(): { state: string; city: string }[] {
  const out: { state: string; city: string }[] = [];
  for (const [stateSlug, cities] of Object.entries(CITIES_BY_STATE)) {
    for (const c of cities) out.push({ state: stateSlug, city: c.slug });
  }
  return out;
}
